services:
  - type: web
    name: get-set-go-holidays
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000